# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  registry = {
    pname = "registry";
    version = "86523039bb1b8e8a8035f0abbb3dccd03a1ff4a1";
    src = fetchFromGitHub {
      owner = "codedownio";
      repo = "General";
      rev = "86523039bb1b8e8a8035f0abbb3dccd03a1ff4a1";
      fetchSubmodules = false;
      sha256 = "sha256-Q0/ySOUHSzr2muX5KvRoPtvFpe936J/ty8yi25W13fg=";
    };
    date = "2025-11-30";
  };
}
